import { CaseStudyCards } from '../components/CaseStudies';
import { Link } from 'react-router-dom';
import { INSIGHTS, SERVICES } from '../content';
import { CLIENTS, CONTACT, EMPLOYERS, MENTIONS, NAME, PREZLO_URL, PREZLO_PORTFOLIOS, REVIEWED, REVIEWED_LABEL } from '../site';
import { NextStep } from '../components/Layout';

export const HOME_FAQS = [
  { q: 'Who is Lopty Pascal?', a: 'Lopty Pascal is a senior digital marketing expert and consultant in Dubai with 10 years of experience and more than 300 projects. His specialism is AI SEO and GEO, and he is the co-founder and builder of Prezlo, an AI visibility platform.' },
  { q: 'What does Lopty Pascal do?', a: 'He offers three services: AI SEO and GEO, hands-on digital marketing as a specialist, and independent advice as a digital marketing consultant.' },
  { q: 'What is Prezlo?', a: 'Prezlo is a platform that makes businesses and professionals easier for AI assistants to find, verify and recommend. Lopty co-founded and built it.' },
  { q: 'Does he promise rankings or AI recommendations?', a: 'No. Nobody controls search results or AI answers. He commits to the work, the method and honest reporting.' },
];
const serviceCopy = [
  { icon: '◎', title: 'Be found in the next era of search.', copy: 'Document your trust signals, position your strongest outcomes, and connect your expertise through knowledge graphs.', tags: 'AI SEO / GEO / Organic search' },
  { icon: '↗', title: 'Turn attention into business.', copy: 'Hands-on paid campaigns, landing pages and conversion tracking, connected to qualified leads and sales.', tags: 'Google Ads / Performance / Tracking' },
  { icon: '⌘', title: 'Find your clearest way forward.', copy: 'An independent look at your marketing, a focused plan, and practical direction for your team or agency.', tags: 'Audits / Strategy / Advisory' },
];
const selectedInsights = ['insights/what-is-geo', 'insights/how-to-get-recommended-by-chatgpt', 'insights/seo-vs-google-ads-dubai'];
const brandLogos: Record<string, { src: string; className?: string }> = {
  'Al Basel Group': { src: '/logos/al-basel.png' },
  'haus & haus': { src: '/logos/haus-and-haus.svg', className: 'haus-logo' },
  'Terra Solis': { src: '/logos/terra-solis.svg', className: 'terra-logo' },
};
const featuredBrands = ['Google', 'MTN', 'Al Basel Group', 'haus & haus', 'Tecworq', 'Prefab UAE (Masah Al Murabaa)', 'Dubai Syndicate', 'Jeffaro', 'Lark Group', 'KOF', 'Accurate Power Group', 'Terra Solis', 'AuditBOT', 'Najd Rent a Car'];
export default function Home() {
  return <div className="home">
    <section className="hero section-shell">
      <div className="hero-copy">
        <p className="eyebrow"><span className="status-dot" /> DUBAI, UAE · WORKING WORLDWIDE</p>
        <p className="hero-role">Senior digital marketing<br className="role-break" /> expert &amp; consultant</p>
        <h1>I help brands<br />get found.<br /><span>And chosen.</span></h1>
        <div className="hero-description"><p className="hero-specialty">Expert in AI SEO / GEO</p><p>I turn your expertise into visibility,<br className="desktop-break" /> trust, and opportunities to grow.</p></div>
        <div className="hero-actions"><a className="btn-primary" href={CONTACT.calendly}>Let’s talk about your growth <span aria-hidden="true">↗</span></a><Link className="btn-secondary" to="/work">Explore my work <span aria-hidden="true">↓</span></Link></div>
        <p className="hero-founder">CO-FOUNDER & BUILDER OF <Link to="/prezlo">prezlo<span>↗</span></Link></p>
      </div>
      <div className="hero-visual">
        <div className="portrait-frame"><span className="portrait-note">STRATEGY. EXECUTION. REAL PEOPLE.</span><img src="/lopty-pascal.webp" srcSet="/lopty-pascal-320.webp 320w, /lopty-pascal.webp 640w" sizes="(min-width: 900px) 460px, 90vw" width="640" height="747" alt="Lopty Pascal, digital marketing consultant and co-founder of Prezlo" fetchPriority="high" /></div>
        <div className="portrait-label"><span className="portrait-mark">↗</span><div><strong>A marketer. A builder.</strong><span>Making visibility work for business.</span></div></div>
      </div>
    </section>
    <div className="trust-reference-strip section-shell"><span className="eyebrow">MY ENTITY SEO PERSPECTIVE, REFERENCED BY</span>{MENTIONS.map(m => <a key={m.url} href={m.url} rel="noopener">{m.publisher} <span aria-hidden="true">↗</span></a>)}</div>
    <section className="client-section section-shell" aria-labelledby="clients-heading"><div className="strip-heading"><p id="clients-heading" className="eyebrow">BRANDS I’VE WORKED WITH</p><Link to="/work" className="plain-link">The work behind the names ↗</Link></div><ul className="brand-grid">{featuredBrands.map(name => <li key={name}>{brandLogos[name] ? <img src={brandLogos[name].src} className={brandLogos[name].className} width="180" height="60" alt={`${name} brand logo`} loading="lazy" /> : <span className="brand-name">{name === 'Prefab UAE (Masah Al Murabaa)' ? <>Prefab UAE<small>Masah Al Murabaa</small></> : name}</span>}</li>)}</ul></section>
    <section className="stats-band"><div className="section-shell stats-grid"><div><strong>10<span> years</span></strong><p>In digital marketing</p></div><div><strong>300<span>+</span></strong><p>Projects across sectors</p></div><div><strong>$20<span> million+</span></strong><p>Client sales from campaign leads*</p></div><div><strong>Built<span> Prezlo</span></strong><p>From practice to product</p></div></div><p className="stats-note section-shell">*Client sales generated through campaign leads, including property transactions. <Link to="/work">How this figure is counted ↗</Link></p></section>
    <section className="section-shell home-section" aria-labelledby="services-heading"><div className="section-heading"><div><p className="eyebrow">HOW I CAN HELP</p><h2 id="services-heading">Good strategy.<br /><span>Better execution.</span></h2></div><p>From the first search to the final decision, I help you connect the dots that turn visibility into growth.</p></div><div className="service-grid">{SERVICES.map((service,i) => <Link to={`/${service.slug}`} className="service-card" key={service.slug}><div className="service-top"><span className="service-icon">{serviceCopy[i].icon}</span><span className="service-number">0{i+1}</span></div><p className="eyebrow">{service.navLabel}</p><h3>{serviceCopy[i].title}</h3><p>{serviceCopy[i].copy}</p><div className="service-bottom"><span>{serviceCopy[i].tags}</span><span aria-hidden="true">↗</span></div></Link>)}</div></section>
    <section className="prezlo-section section-shell" aria-labelledby="prezlo-heading"><div className="prezlo-copy"><p className="eyebrow">BEYOND CONSULTING · BUILDING PREZLO</p><h2 id="prezlo-heading">The future of search<br />is a conversation.</h2><p>I co-founded and built Prezlo to help brands and professionals be found, verified and recommended by AI. It brings the problem I work on every day into a product.</p><div className="prezlo-tags"><span>Trust signals</span><span>Knowledge graphs</span><span>AI visibility</span></div><div className="prezlo-actions"><a href={PREZLO_URL} target="_blank" rel="noopener noreferrer" className="btn-primary">Try Prezlo <span aria-hidden="true">↗</span></a><Link to="/prezlo" className="btn-secondary">How I built it <span aria-hidden="true">↗</span></Link></div><p className="prezlo-adoption"><strong>200+ agencies and consultants</strong> use Prezlo for their GEO work. <a href={PREZLO_PORTFOLIOS} target="_blank" rel="noopener noreferrer">Explore Prezlo portfolios ↗</a></p></div><div className="prezlo-art"><span className="prezlo-logotype">prezlo<span>✳</span></span><p>Make your expertise discoverable.</p><div className="prezlo-flow"><span>Your brand</span><span aria-hidden="true">↓</span><strong>Clear identity. Trusted signals.</strong><span aria-hidden="true">↓</span><div><span>ChatGPT</span><span>Perplexity</span><span>Gemini</span></div></div><span className="prezlo-art-note">A PLATFORM BUILT BY LOPTY PASCAL</span></div></section>
    <section className="section-shell home-section about-section"><div><p className="eyebrow">THE PERSON BEHIND THE WORK</p><h2>A builder’s mindset.<br /><span>A marketer’s instinct.</span></h2></div><div><p>I’m a senior digital marketing expert and consultant based in Dubai, with expertise in AI SEO and GEO. I work directly with businesses to make their search presence clearer, their campaigns more accountable, and their next move easier to see.</p><p>My background includes roles at {EMPLOYERS.join(', ')} and projects across real estate, travel, car rental, SaaS, hospitality and healthcare.</p><Link to="/about" className="plain-link">A little more about me ↗</Link><div className="client-list"><p className="eyebrow">MORE CLIENT PROJECTS</p><p>{CLIENTS.filter(c => !['Al Basel Group','haus & haus','AuditBOT','Terra Solis','Najd Rent a Car'].includes(c)).join(' · ')}</p></div></div></section>
    <CaseStudyCards />
    <section className="evidence-section"><div className="section-shell home-section"><div className="section-heading"><div><p className="eyebrow">IN THE INDUSTRY CONVERSATION</p><h2>Ideas that travel<br /><span>beyond this website.</span></h2></div><p>Independent publications have referenced my perspective on entities, identity and the changing search landscape.</p></div><div className="mention-grid">{MENTIONS.map(m => <a href={m.url} className="mention-card" rel="noopener" key={m.url}><div><strong>{m.publisher}</strong><span aria-hidden="true">↗</span></div><h3>{m.title}</h3><p>{m.summary}</p><small>{m.published} · Read the original reference</small></a>)}</div></div></section>
    <section className="section-shell home-section"><div className="section-heading"><div><p className="eyebrow">NOTES ON WHAT’S NEXT</p><h2>A clearer view of search.</h2></div><Link to="/insights" className="plain-link">All insights ↗</Link></div><div className="insight-grid">{selectedInsights.map((slug,i) => {const p=INSIGHTS.find(p => p.slug===slug)!;return <Link to={`/${slug}`} className="insight-card" key={slug}><span className="eyebrow">0{i+1} / FIELD NOTES</span><h3>{p.h1}</h3><span className="plain-link">Read the article ↗</span></Link>})}</div></section>
    <section className="section-shell home-section faq-section"><div><p className="eyebrow">A FEW THINGS YOU MIGHT ASK</p><h2>Let’s make it clear.</h2><p className="review-note">Reviewed <time dateTime={REVIEWED}>{REVIEWED_LABEL}</time> by {NAME}.</p></div><div>{HOME_FAQS.map(f => <details key={f.q}><summary>{f.q}<span aria-hidden="true">+</span></summary><p>{f.a}</p></details>)}</div></section>
    <div className="section-shell"><NextStep heading="Let’s make your next move count." /></div>
  </div>;
}
